# Generated by Django 3.2.9 on 2021-11-28 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('rut_admin', models.CharField(max_length=10)),
                ('primer_nombre_admin', models.CharField(max_length=30)),
                ('segundo_nombre_admin', models.CharField(max_length=30)),
                ('apellido_paterno_admin', models.CharField(max_length=30)),
                ('apellido_materno_admin', models.CharField(max_length=30)),
                ('correo_admin', models.CharField(max_length=30)),
                ('n_tel_admin', models.CharField(max_length=30)),
                ('sexo_admin', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('primer_nombre_cliente', models.CharField(max_length=30)),
                ('segundo_nombre_cliente', models.CharField(max_length=30)),
                ('apellido_paterno_cliente', models.CharField(max_length=30)),
                ('apellido_materno_cliente', models.CharField(max_length=30)),
                ('correo_cliente', models.CharField(max_length=30)),
                ('n_tel_cliente', models.CharField(max_length=30)),
                ('sexo_cliente', models.CharField(max_length=1)),
                ('nacionalidad_cliente', models.CharField(max_length=50)),
                ('n_acompanante_cliente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_depto', models.AutoField(primary_key=True, serialize=False)),
                ('pais_depto', models.CharField(max_length=30)),
                ('cuidad_depto', models.CharField(max_length=30)),
                ('direccion_depto', models.CharField(max_length=30)),
                ('nombre_depto', models.CharField(max_length=30)),
                ('n_telefono_depto', models.CharField(max_length=10)),
                ('estado_depto', models.CharField(max_length=15)),
                ('descripcion_depto', models.TextField()),
                ('img_dept', models.ImageField(null=True, upload_to='deptos')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto_pago', models.IntegerField()),
                ('detalle_pago', models.CharField(max_length=30)),
                ('fecha_pago', models.DateField()),
                ('check_in', models.CharField(max_length=30)),
                ('check_out', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turismo.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioExtra',
            fields=[
                ('id_serv', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_serv', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_trans', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_vehiculo_trans', models.CharField(max_length=15)),
                ('valor_trans', models.IntegerField()),
                ('cantidad_asientos_trans', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('estado_reserva', models.BooleanField(default=True)),
                ('costo_reserva', models.IntegerField()),
                ('comentario_reserva', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turismo.cliente')),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turismo.departamento')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turismo.detallepago')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turismo.servicioextra')),
                ('trans', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turismo.transporte')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_hab', models.CharField(max_length=3)),
                ('cantidad_piezas_hab', models.CharField(max_length=2)),
                ('cantidad_bano_hab', models.CharField(max_length=2)),
                ('metros_cuadrado_hab', models.CharField(max_length=2)),
                ('descripcion_hab', models.TextField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turismo.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('rut_funcionario', models.CharField(max_length=10)),
                ('primer_nombre_funcionario', models.CharField(max_length=30)),
                ('segundo_nombre_funcionario', models.CharField(max_length=30)),
                ('apellido_paterno_funcionario', models.CharField(max_length=30)),
                ('apellido_materno_funcionario', models.CharField(max_length=30)),
                ('correo_funcionario', models.CharField(max_length=30)),
                ('n_tel_funcionario', models.CharField(max_length=30)),
                ('sexo_funcionario', models.CharField(max_length=1)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turismo.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='detallepago',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turismo.funcionario'),
        ),
        migrations.CreateModel(
            name='Acompañante',
            fields=[
                ('id_acom', models.AutoField(primary_key=True, serialize=False)),
                ('rut_acom', models.CharField(max_length=10)),
                ('primer_nombre_acom', models.CharField(max_length=30)),
                ('segundo_nombre_acom', models.CharField(max_length=30)),
                ('apellido_paterno_acom', models.CharField(max_length=30)),
                ('apellido_materno_acom', models.CharField(max_length=30)),
                ('correo_acom', models.CharField(max_length=30)),
                ('n_tel_acom', models.CharField(max_length=30)),
                ('sexo_acom', models.CharField(max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turismo.cliente')),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turismo.departamento')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turismo.reserva')),
            ],
        ),
    ]
