# Generated by Django 3.2.9 on 2021-11-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0003_auto_20211128_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(max_length=30),
        ),
    ]
