# Generated by Django 3.2.9 on 2021-11-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0005_auto_20211128_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='depto',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='servicio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='trans',
            field=models.CharField(max_length=20),
        ),
    ]
