# Generated by Django 3.2.9 on 2021-11-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0006_auto_20211128_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='check_in',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='check_out',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
